name: wlwwt-wordpress-base
type: wordpress
docroot: public
php_version: "8.2"
timezone: "Europe/Berlin"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
composer_version: "2"
omit_containers: [ddev-ssh-agent]
disable_settings_management: true
